### ISSUE TITLE
Add unit + integration testing

### ISSUE THREAD

**Issue by willhonaker** [GeodataTools/geodata#22]
Before adding too much new functionality, we should implement unit tests + integration tests so that we can easily ensure that all functions + e2e download processes still work when adding new features.

For reference:
https://docs.python.org/3/library/unittest.html
https://realpython.com/python-testing/

Each individual function (Era5's get_data, Merra2's cutout preparation) should be tested, as well as each e2e process (ie Merra2's `slv_radiation_monthly`, from Dataset declaration to output generation).

**Comment by east-winds** [comment]
Addressed with #81
