### ISSUE TITLE
`config.py` seems missing and code currently doesn't import

### ISSUE THREAD

**Issue by fperez** [GeodataTools/geodata#76]
I did a local installation (in pip dev mode) after building the supplied conda env, but currently geodata won't import...

```python
import geodata
```

produces

```python-traceback

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Input In [1], in <cell line: 1>()
----> 1 import geodata

File ~/tmp/geodata/geodata/__init__.py:25, in <module>
     17 """
     18 GEODATA
     19 
     20 Geospatial Data Collection and "Pre-Analysis" Tools
     21 """
     23 from __future__ import absolute_import
---> 25 from .cutout import Cutout
     26 from .mask import Mask
     27 from .dataset import Dataset

File ~/tmp/geodata/geodata/cutout.py:37, in <module>
     35 from shapely.geometry import box
     36 from six import iteritems
---> 37 from . import config #pylint: disable=E0611
     39 from .convert import (
     40 	convert_cutout,
     41 	heat_demand,
   (...)
     46 	soil_temperature
     47 	)
     49 from .preparation import (
     50 	cutout_prepare,
     51 	cutout_produce_specific_dataseries,
     52 	cutout_get_meta,
     53 	cutout_get_meta_view
     54 	)

ImportError: cannot import name 'config' from partially initialized module 'geodata' (most likely due to a circular import) (/Users/fperez/tmp/geodata/geodata/__init__.py)
```

**Comment by east-winds** [comment]
Did you create a `config.py` file from `config-default.py` prior to installation? See: https://github.com/GeodataTools/geodata/blob/master/doc/general/packagesetup.md#downloading-and-configuring-geodata

**Comment by fperez** [comment]
Ah, no, missed that step, thanks a lot!

I'd suggest however de-coupling the import of the code from user-specific configuration of this kind. It will make it much trickier to deploy this with standard mechanisms (from running your test suites in CI to deploying the tool in the cloud on generic Docker infrastructure)...

In general, this issue is best handled by having the package have some reasonable internal defaults, optionally overridden by a user-configurable file read at run-time from the user's `$HOME`. Happy to discuss further if you'd like.

**Comment by fperez** [comment]
For reference, [here is how we handle this problem in Jupyter](https://docs.jupyter.org/en/latest/use/jupyter-directories.html) in case that's helpful. You can see both our various choices as well as (at the bottom) the code in our APIs that handles these issues if it's helpful.

**Comment by east-winds** [comment]
This has been addressed through the use of an environment variable in the PR #80
